export const colors = [
  { h: 25, name: 'stone', s: '5%' },
  { h: 0, name: 'neutral', s: '0%' },
  { h: 240, name: 'zinc', s: '5%' },
  { h: 220, name: 'gray', s: '8%' },
  { h: 215, name: 'slate', s: '16%' },
  { h: 0, name: 'red' },
  { h: 25, name: 'orange' },
  { h: 38, name: 'amber' },
  { h: 45, name: 'yellow' },
  { h: 85, name: 'lime' },
  { h: 140, name: 'green' },
  { h: 160, name: 'emerald' },
  { h: 175, name: 'teal' },
  { h: 185, name: 'cyan' },
  { h: 198, name: 'sky' },
  { h: 218, name: 'blue' },
  { h: 238, name: 'indigo' },
  { h: 258, name: 'violet' },
  { h: 270, name: 'purple' },
  { h: 290, name: 'fuschia' },
  { h: 330, name: 'pink' },
  { h: 350, name: 'rose' },
]
